language: php

# php compatibility
php: ["7.2", "7.3", "7.4", "8.0"]

dist: focal

services:
  - mysql
  - docker

env:
  - PHP_VERSION_FULL_BUILD="8.0"

before_script:
  # disable xdebug
  - phpenv config-rm xdebug.ini || true
  # ms sql server, run first to allow server run while install other things
  - docker pull microsoft/mssql-server-linux
  - docker run --name dbal-mssql -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password-123456' -p 1433:1433 -d microsoft/mssql-server-linux
  - docker ps -a
  # apt setup including microsoft packages
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee -a /etc/apt/sources.list.d/microsoft.list
  - sudo apt-get update -q -q
  # ms sql server php driver, run before install msodbcsql17
  - sudo apt install -q -y unixodbc-dev
  - pecl channel-update pecl.php.net
  - pecl search sqlsrv
  - pecl install sqlsrv pdo_sqlsrv
  # install msodbcsql17
  - apt-cache policy msodbcsql17 mssql-tools unixodbc php-sybase
  - sudo ACCEPT_EULA=Y apt-get install -q -y msodbcsql17 mssql-tools unixodbc php-sybase
  # test connections
  - docker exec dbal-mssql /opt/mssql-tools/bin/sqlcmd -U sa -P 'Password-123456' -Q "SELECT @@VERSION"
  - php tests/sqlsrv-direct-connection.php localhost sa 'Password-123456'
  # project
  - phpenv config-rm xdebug.ini
  - composer update --no-interaction --prefer-dist

script:
  - cp tests/.env.travis tests/.env
  - |
    if [[ $TRAVIS_PHP_VERSION == $PHP_VERSION_FULL_BUILD ]]; then
      vendor/bin/phpcs -sp
      vendor/bin/php-cs-fixer fix --using-cache=no --dry-run --verbose
      php -dzend_extension=xdebug.so -dxdebug.mode=coverage vendor/bin/phpunit --coverage-clover=coverage.xml --verbose
      php vendor/bin/phpstan analyse --no-interaction --no-progress
    else
      php vendor/bin/phpunit --testdox --verbose
    fi

after_script:
  # upload to scrutinizer
  - |
    if [[ $TRAVIS_PHP_VERSION == $PHP_VERSION_FULL_BUILD ]]; then
      wget -q https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.xml
    fi

notifications:
  email: false
