# use sudo since we will use docker
sudo: required

language: php

# php compatibility
php:
  - 5.6
  - 7.0
  - 7.1

services:
  - mysql
  - docker

before_script:
  - docker pull microsoft/mssql-server-linux
  - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=secret' -p 1433:1433 -d microsoft/mssql-server-linux
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - php -i
  - docker ps -a
  - cp tests/.env.travis tests/.env
  - mkdir -p build/tests/
  - vendor/bin/parallel-lint sources/ tests/
  - vendor/bin/phpcs -sp sources/ tests/
  - vendor/bin/php-cs-fixer fix --using-cache=no --dry-run --verbose
  - vendor/bin/phpunit --coverage-text --coverage-clover=build/tests/coverage.xml

after_script:
  - if [[ $TRAVIS_PHP_VERSION == '5.6' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover build/tests/coverage.xml; fi

notifications:
  email: false
